### ISSUE TITLE
Cordova 10.x with cordova-plugin-whitelist

### ISSUE THREAD

**Issue by kzimny** [apache/cordova-plugin-whitelist#61]
This plugin is still required in cordova 10.x, it will be installed and added automatically to package.json with command `cordova platform add android | ios`

![image](https://user-images.githubusercontent.com/12007674/121678891-0c0e7780-cab8-11eb-9ba9-146471e218bb.png)

**Comment by jcesarmobile** [comment]
not sure what the question is, the plugin is still used by cordova-android 9 (latest at the moment)
will be skipped on next major release of cordova-android (10) because it's being integrated.
it's not used in cordova-ios because it was integrated long ago

**Comment by almothafar** [comment]
Just a silly question, is there anything to do in config.xml file? like is it enough to remove this plugin or do I need to do some migrations?

**Comment by kzimny** [comment]
I'm working with cordova-android 10.x. When I remove cordova-plugin-whitelist from config.xml the application does not work as expected. So it seems that cordova-plugin-whitelist plugin is still used AND IS INSTALLED WITH `cordova platform add android` command as shown in image above. Try to remove the plugin from config.xml and check if your application is still working fine.

**Comment by almothafar** [comment]
@kzimny I'm not talking about this, in your image I see you still use 9.1.0, what I'm talking about is "cordova-android 10" which is still not released not "cordova 10" 

![image](https://user-images.githubusercontent.com/13887564/124380712-d596d780-dcc6-11eb-9b35-92040b2e0c65.png)

for this plugin, you maybe need to try to use 1.3.5 now it is released since 3 days ago, it should lock it for only cordova-android < 10 

So my question with the upcoming cordova-android 10, is there something I need to do when it got released?

**Comment by erisu** [comment]
> Just a silly question, is there anything to do in config.xml file? like is it enough to remove this plugin or do I need to do some migrations?

@almothafar  In short, no. The settings that you have defined in `config.xml` will continue to work. When you use Cordova-Android 10, you only need to remove the plugin with `cordova plugin remove`

All we did was migrate the plugin's source code into the core of Cordova-Android. Additionaly, the class, variable, & method names, on the native side of things, were renamed from whitelist to allowlist.

Since the `config.xml` settings didnt use these keywords, you shouldnt see any affect, as an app dev.

If you were writting your own native plugin and for some reason calling directly or extended the WhitelistPlugin or Whitelist class, then you might have to make some small changes. But in most cases I dont think anyone are using these classes directly.

**Comment by CodeWithOz** [comment]
I'm getting an error that looks like it's caused by the same cordova-android 10 changes, this is an example of my error message:
```
> Task :app:compileDebugJavaWithJavac
/Users/vagrant/git/platforms/[REDACTED]/app/src/main/java/org/apache/cordova/whitelist/WhitelistPlugin.java:25: error: cannot find symbol
import org.apache.cordova.Whitelist;
                         ^
  symbol:   class Whitelist
  location: package org.apache.cordova
```

Should I create a separate issue for my case?

**Comment by kzimny** [comment]
@CodeWithOz maybe the reference to WhileList plugin is still in you package.json file? You only need to remove the plugin with `cordova plugin remove`
